### ISSUE TITLE
다운로드 중간에 오류가 나는 항목이 있음

### ISSUE THREAD

**Issue by existmaster** [RyuaNerin/DaruDaru#10]
- 전권 다운로드 시, 몇몇 중간에 권에 에러가 있음
- 시간을 두고 재시도를 하였으나 다시 에러로 바뀜

![image](https://user-images.githubusercontent.com/4814719/75216016-edf30a00-57d5-11ea-8271-f21c10523012.png)

![image](https://user-images.githubusercontent.com/4814719/75216025-f9decc00-57d5-11ea-8e6d-68f9957839e5.png)

**Comment by RyuaNerin** [comment]
마나모아쪽에서 일부 페이지가 누락된 경우입니다.

**Comment by existmaster** [comment]
- 해당 링크를 복사하여 웹에서 보는 경우에는 잘 보여집니다.
- https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=366852

**Comment by RyuaNerin** [comment]
검토해보겠습니다.

**Comment by RyuaNerin** [comment]
문제 수정하였습니다. 감사합니다.
