### ISSUE TITLE
다운로드 오류

### ISSUE THREAD

**Issue by existmaster** [RyuaNerin/DaruDaru#11]
- 1.1.0.15 버전 업데이트로 대부분의 다운로드 중 오류는 해결하였음
- 특정 만화의 한 권은 여전히 오류를 나타냄

https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=103923

**Comment by RyuaNerin** [comment]
7번 페이지가 누락된것으로 보입니다.

- [https://drive.google.com/uc?export=view&id=1Mi1o7tkSTAVzdCPUSYkwtjcB5Yyi1IiL](https://drive.google.com/uc?export=view&id=1Mi1o7tkSTAVzdCPUSYkwtjcB5Yyi1IiL)
- [https://filecdn.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg](https://filecdn.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg)
- CDN
  - [https://cdnkikiki.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick](https://cdnkikiki.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick)
  - [https://cdnchance.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick](https://cdnchance.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick)
  - [https://cdnbegin.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick](https://cdnbegin.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick)
  - [https://cdnstretch.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick](https://cdnstretch.xyz/upload/75771_6_a2e2df94ec5f658f93c5f70d45aa0ba5.jpg?quick)

**Comment by RyuaNerin** [comment]
#13

**Comment by RyuaNerin** [comment]
[v1.1.0.22](https://github.com/RyuaNerin/DaruDaru/releases/tag/1.1.0.22) 에서 오류 무시 기능이 추가되었습니다.
