### ISSUE TITLE
오류 넘기기 기능은 없을까요?

### ISSUE THREAD

**Issue by bronzepenny** [RyuaNerin/DaruDaru#13]
간혹가다 한,두 페이지가 없어서 한권 전체가 다운로드가 안되는 경우가 있습니다.

그럴때 오류 무시하고 완료시키는 방법도 있으면 좋을 것 같습니다.

**Comment by RyuaNerin** [comment]
고려해보겠습니다.

**Comment by RyuaNerin** [comment]
[v1.1.0.22](https://github.com/RyuaNerin/DaruDaru/releases/tag/1.1.0.22) 에서 추가되었습니다.
