### ISSUE TITLE
일부 URL 다운로드 오류

### ISSUE THREAD

**Issue by duach** [RyuaNerin/DaruDaru#14]
츠구모모 11권 특별편1:
https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=29150
투러브 트러블 4권 - 전:
https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=69801

해당 URL에서 다운로드 오류가 나타나고 있습니다.

**Comment by RyuaNerin** [comment]
- 츠구모모 11권 특별편
  - [24 페이지](https://2.bp.blogspot.com/-8ZXvDMzzLlo/VpMJTRAQNuI/AAAAAAADQ8M/cs_zNM5Vzxg/s1600/24.jpeg) 가 누락되었습니다
- 투러브 트러블 4권 - 전
  - [18 페이지](https://4.bp.blogspot.com/-bFdw5oB_o70/VgPuA6hGypI/AAAAAAAA4_w/8Q4ncdcvhmQ/s1600/ToLOVE%25E3%2582%258B%2B26-18.jpg) 가 누락되었습니다.

오류넘기기 기능(#13) 을 추가 예정중입니다.

**Comment by RyuaNerin** [comment]
[v1.1.0.22](https://github.com/RyuaNerin/DaruDaru/releases/tag/1.1.0.22) 에서 오류 무시 기능이 추가되었습니다.
