### ISSUE TITLE
마나모아 다운이 안됩니다ㅠㅠ

### ISSUE THREAD

**Issue by cocoman1111** [RyuaNerin/DaruDaru#15]
![캡처](https://user-images.githubusercontent.com/35674951/76635551-fc3d7600-658a-11ea-93ce-1e5004cac57f.PNG)

다운로드 시, 봇 체크 창이 떴었는데..

이제는 체크창은 뜨나, 그 창이

웹 페이지 탐색 취소 되었습니다. 라고 뜨면서 접속이 안되네요..

수정부탁드려도 될까요 ㅠㅠ 다운 받고 싶습니다

**Comment by RyuaNerin** [comment]
설정에서 **우회용 호스트 설정** 변경해주세요.

**Comment by cocoman1111** [comment]
manamoa30.net으로 설정했는데 저렇게 나왔었어요..

오늘 다시 해보니
-------------------------------------------------
Please enable cookies.



One more step

Please complete the security check to access manamoa30.net
 





   
 

 

 
  



Why do I have to complete a CAPTCHA?

Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.


What can I do to prevent this in the future?
 
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.
 

Cloudflare Ray ID: 573bdb74fd9698ab • Your IP: 121.176.195.110 • Performance & security by Cloudflare 
-----------------------------------------------------
이렇게 뜨네요.. ㅠㅠ

**Comment by cocoman1111** [comment]
감사합니다. 어제 30으로 고쳐서 햇다고 생각햇는데 아니였나봅니다.
