### ISSUE TITLE
실행이 안됩니다. 도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by cocoman1111** [RyuaNerin/DaruDaru#18]
안녕하세요..

오늘 윈도우 포맷을 하고나서 다시 다운받아서 설치하려고 하는데..

실행시키니 프로그램이 켜졌다 꺼지고

 크롬창뜨면서 https://github.com/RyuaNerin/DaruDaru/releases/tag/1.1.0.25 으로 연결되네요.

제가 어디를 잘못한걸까요 ㅠㅠ

**Comment by RyuaNerin** [comment]
이제 정상 실행 되실거에요.
