### ISSUE TITLE
저 답변을 받았습니다만., 여전히 같은 현상으로 실행이 안됩니다.

### ISSUE THREAD

**Issue by cocoman1111** [RyuaNerin/DaruDaru#19]
1시간전에 답변 하신 걸 보고 다시 다운받아서 해봤는데요..

여전히 프로그램 켜졌다가 꺼지면서

https://github.com/RyuaNerin/DaruDaru/releases/tag/1.1.0.26  으로 연결이 됩니다..

관리자 권한도 동일하구요.. 

프로그램 구동시 작업관리자에도 올라오지도 않습니다 ㅠㅠ...

뭔지 모르겟습니다.  ㅠㅠㅠㅠ

**Comment by RyuaNerin** [comment]
죄송합니다 버전관리가 잘못되고 있었습니다. 새로 업데이트 진행해주시면 이용 가능하십니다.

https://github.com/RyuaNerin/DaruDaru/releases/latest

**Comment by sun3695** [comment]
저도 똑같은 현상이 일어납니다...
이전엔 안 그랬는데
다시 다운그레이드 해주시면 감사하겠습니다
이전 버젼 잘 쓰고 있었는데 왜..;;;

**Comment by sun3695** [comment]
감사합니다.
항상 화이팅입니다
당신은 저희를 구원해주는 신입니다

**Comment by cocoman1111** [comment]
감사합니다. 잘 작동됩니다. ^^
꾸 m(_ _)m 벅
