### ISSUE TITLE
exe실행시 작동이 중지되었다고 뜹니다

### ISSUE THREAD

**Issue by bono9906** [RyuaNerin/DaruDaru#20]
왜이러는걸까요....? 윈도우7 32비트 사용중입니다 관리자권한으로 실행해봐도 작동이 중지되었다는 창만 뜨네욥

**Comment by RyuaNerin** [comment]
개발 및 테스트 환경이 윈도우 10 외엔 없어서 이외의 버전은 공식적으로 지원해드리고 있지 않습니다.
시간나는대로 확인은 해보겠으나, 윈도우 10 업데이트를 권장해드립니다.

**Comment by bono9906** [comment]
> 개발 및 테스트 환경이 윈도우 10 외엔 없어서 이외의 버전은 공식적으로 지원해드리고 있지 않습니다.
> 시간나는대로 확인은 해보겠으나, 윈도우 10 업데이트를 권장해드립니다.

귀찮아서 줄곧 미뤘는데 해야겠네요. 답변 감사합니다^^
