### ISSUE TITLE
홈페이지 수동 접속, 웹페이지 탐색이 취소되었습니다.

### ISSUE THREAD

**Issue by bronzepenny** [RyuaNerin/DaruDaru#21]
링크 드래그할 시 홈페이지 수동 접속 창이 뜨는데 
위와 같은 오류 메시지가 나오면서, 프로그램 상에서도 오류판정 나서 다운로드가 되지 않습니다.
현재 마루마루 사이트는 크롬 vpn을 통해서 접속은 가능합니다.

**Comment by RyuaNerin** [comment]
크롬에서 vpn 없이 접속이 되는 주소로 `우회용 호스트 설정` 에 입력해주세요. DaruDaru 는 vpn 등의 우회 환경은 제공해드리고 있지 않습니다.
