### ISSUE TITLE
기능건의

### ISSUE THREAD

**Issue by CherryDrops** [RyuaNerin/DaruDaru#23]
안녕하세요 해당 앱 감사히 잘 쓰고 있습니다.
기능 건의 가능할까요?

1. 검색에 완결 여부 소팅 가능
 - 완결작 위주로 보고 싶은데 아예 소팅이 가능하면 더 편할것 같습니다.

2. 다운로드시 파싱되지 않은 주소는 임시 저장했다가 앱 재기동시 자동 추가
 - 많은 파일을 받는경우, 혹은 15줄 정도의 웹주소를 복사하면 종종 크래시가 납니다.
   이경우 파싱되지 않은 주소는 다시 받기가 까다로운데 해당 기능 추가가 가능할까요?

감사합니다.

**Comment by RyuaNerin** [comment]
2번 임시저장 기능은 시간이 더 걸릴 것 같습니다.
복사 후 크래시 문제는 수정되었으니 큰 불편은 없으실거라 생각됩니다.

**Comment by CherryDrops** [comment]
확인했습니다. 해당 이슈 클로즈 하겠습니다. 감사합니다.
