### ISSUE TITLE
https:// 중복 문제

### ISSUE THREAD

**Issue by levelhoon** [RyuaNerin/DaruDaru#37]
https://manamoa52.net/bbs/page.php?hid=manga_detail&manga_id=10967

모든 회차수 전체다운로드 기능이 있다길래
를 다운로드하려고 시도했었습니다.

https://manamoa52.net/bbs/page.php?hid=manga_detail&manga_id=10967
https://https://manamoa52.net/bbs/page.php?hid=manga_detail&manga_id=10967
일단 인풋 바에 입력해서 넣었을때, 주소가 위 주소 중 두번째 처럼 https://가 더 추가되는 것을 알 수 있었습니다.

그리고 제가 이 것을 사용하려고 시도한 이유는 가끔 사이트에서 이미지가 정상적으로 노출되지않기때문에 다운받아서 보려고했었던 것인데,
잘 되는지 확인좀 부탁합니다.

**Comment by RyuaNerin** [comment]
우회용 호스트 설정에서 https:// 를 뺴고 `manamoa52.net` 만 입력해주세요.
